# Generated by Django 5.1 on 2024-09-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_slaider_remove_headertext_image1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slaider',
            options={'verbose_name': 'Slaider', 'verbose_name_plural': 'Slaider'},
        ),
        migrations.RemoveField(
            model_name='slaider',
            name='slide1',
        ),
        migrations.AddField(
            model_name='slaider',
            name='slider',
            field=models.ImageField(blank=True, null=True, upload_to='slider'),
        ),
    ]
