# Generated by Django 5.1 on 2024-09-28 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_slaider_options_remove_slaider_slide1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slaider',
            new_name='Slider',
        ),
    ]
