# Generated by Django 5.1 on 2024-09-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_slider_slider_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('description1', models.TextField(blank=True, max_length=250, null=True)),
                ('description2', models.TextField(blank=True, max_length=250, null=True)),
                ('years', models.CharField(max_length=55)),
                ('text', models.TextField(max_length=55)),
                ('gallery_image1', models.ImageField(blank=True, null=True, upload_to='about')),
                ('gallery_image2', models.ImageField(blank=True, null=True, upload_to='about')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
            },
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('days1', models.CharField(max_length=60)),
                ('days2', models.CharField(max_length=60)),
                ('open_time1', models.CharField(max_length=60)),
                ('open_time2', models.CharField(max_length=60)),
                ('close_time', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Opening Hours',
                'verbose_name_plural': 'Opening Hours',
            },
        ),
        migrations.CreateModel(
            name='OurClinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('url', models.URLField(blank=True, max_length=255)),
                ('description1', models.TextField(blank=True, max_length=250, null=True)),
                ('description2', models.TextField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Our Clinic',
                'verbose_name_plural': 'Our Clinic',
            },
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviews_class1', models.CharField(blank=True, max_length=400, null=True)),
                ('reviews_class2', models.CharField(blank=True, max_length=400, null=True)),
                ('reviews_class3', models.CharField(blank=True, max_length=400, null=True)),
                ('reviews_class4', models.CharField(blank=True, max_length=400, null=True)),
                ('reviews_class5', models.CharField(blank=True, max_length=400, null=True)),
                ('reviews_class6', models.CharField(blank=True, max_length=400, null=True)),
                ('name', models.CharField(max_length=45)),
                ('position', models.CharField(max_length=60)),
                ('description1', models.TextField(blank=True, max_length=250, null=True)),
                ('description2', models.TextField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image')),
            ],
            options={
                'verbose_name': 'Patients',
                'verbose_name_plural': 'Patients',
            },
        ),
        migrations.CreateModel(
            name='Socials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('url', models.URLField(blank=True, max_length=255)),
                ('html_class', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Social',
                'verbose_name_plural': 'Socials',
            },
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('icon_class', models.CharField(blank=True, help_text='FontAwesome icon', max_length=50, null=True)),
                ('data', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Timeline',
                'verbose_name_plural': 'Timeline',
            },
        ),
        migrations.AlterModelOptions(
            name='animatedinfo',
            options={'verbose_name': 'Animated Info', 'verbose_name_plural': 'Animated Info'},
        ),
    ]
