# Generated by Django 5.1 on 2024-09-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_about_openinghours_ourclinic_patients_socials_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='patient'),
        ),
    ]
