# Generated by Django 5.1 on 2024-09-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_patients_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='gallery_image1',
            field=models.ImageField(blank=True, null=True, upload_to='image1'),
        ),
        migrations.AlterField(
            model_name='about',
            name='gallery_image2',
            field=models.ImageField(blank=True, null=True, upload_to='image2'),
        ),
    ]
