# Generated by Django 5.1 on 2024-09-30 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_about_gallery_image1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeline',
            name='tag',
        ),
    ]
