# Generated by Django 5.1 on 2024-09-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_timeline_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description1', models.TextField(blank=True, max_length=250, null=True)),
                ('description2', models.TextField(blank=True, max_length=250, null=True)),
                ('description3', models.TextField(blank=True, max_length=250, null=True)),
                ('icon_class', models.CharField(blank=True, help_text='FontAwesome icon', max_length=50, null=True)),
                ('link_url', models.URLField(blank=True, null=True)),
                ('data', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Timeline1',
                'verbose_name_plural': 'Timeline1',
            },
        ),
        migrations.CreateModel(
            name='Timeline2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description1', models.TextField(blank=True, max_length=250, null=True)),
                ('description2', models.TextField(blank=True, max_length=250, null=True)),
                ('icon_class', models.CharField(blank=True, help_text='FontAwesome icon', max_length=50, null=True)),
                ('data', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Timeline2',
                'verbose_name_plural': 'Timeline2',
            },
        ),
        migrations.RemoveField(
            model_name='ourclinic',
            name='description1',
        ),
        migrations.RemoveField(
            model_name='ourclinic',
            name='description2',
        ),
        migrations.AddField(
            model_name='ourclinic',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='ourclinic',
            name='name_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ourclinic',
            name='url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
