# Generated by Django 5.1 on 2024-09-30 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_timeline1_timeline2_remove_ourclinic_description1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ourclinic',
            old_name='description',
            new_name='address',
        ),
    ]
