# Generated by Django 5.1.1 on 2024-11-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_patients_reviews_class6_alter_patients_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourclinic',
            name='url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
